--- 
repo: openworm/owmeta
shortDescription: "Unified, simple data access python library for data & facts about C. elegans anatomy"
coordinator: stephen@openworm.org
outputs: 
  - openworm/CElegansNeuroML
  - openworm/ChannelWorm
parent:
  - openworm/OpenWorm
children:
  - openworm/ChannelWorm
